Group Member app. tamamlandı.
omursahin/project_system pull request #23
Opened 2023-05-10 10:15 UTC by sumeyye-sahin

2023-05-15 08:14 UTC, omursahin requested changes

2023-05-15 08:14 UTC, omursahin commented on group_member/models.py
> +        return self.member.first_name + " " + self.member.last_name \
yalnızca grup adı ve member'ın identication_number alanları olsun. Birleştirirken de "+" yerine "%s-%s" %(self.group.title, self.member.identication_number) yöntemini kullanın.

2023-05-15 20:28 UTC, PoyraUmut commented on group_member/models.py
> +        return self.member.first_name + " " + self.member.last_name \
Düzelttik hocam. 👍

2023-05-17 08:12 UTC, omursahin approved these changes

2023-05-17 08:15 UTC, merged